var annotated_dup =
[
    [ "_os_event_", "struct__os__event__.html", "struct__os__event__" ],
    [ "GPIO_ConfigTypeDef", "struct_g_p_i_o___config_type_def.html", "struct_g_p_i_o___config_type_def" ],
    [ "mdns_info", "structmdns__info.html", "structmdns__info" ],
    [ "tmElements", "structtm_elements.html", "structtm_elements" ],
    [ "tsActuator", "structts_actuator.html", "structts_actuator" ],
    [ "tsActuatorTaskRequest", "structts_actuator_task_request.html", "structts_actuator_task_request" ],
    [ "tsBehaviourTaskConfiguration", "structts_behaviour_task_configuration.html", "structts_behaviour_task_configuration" ],
    [ "tsConfiguration", "structts_configuration.html", "structts_configuration" ],
    [ "tsDevice", "structts_device.html", "structts_device" ],
    [ "tsDeviceTimingChange", "structts_device_timing_change.html", "structts_device_timing_change" ],
    [ "tsHTTPControl", "structts_h_t_t_p_control.html", "structts_h_t_t_p_control" ],
    [ "tsHttpRequest", "structts_http_request.html", "structts_http_request" ],
    [ "tsListMember", "structts_list_member.html", "structts_list_member" ],
    [ "tsMemQueueMessage", "structts_mem_queue_message.html", "structts_mem_queue_message" ],
    [ "tsNetworkEvent", "structts_network_event.html", "structts_network_event" ],
    [ "tsNetworkRule", "structts_network_rule.html", "structts_network_rule" ],
    [ "tsPlatformTaskConfiguration", "structts_platform_task_configuration.html", "structts_platform_task_configuration" ],
    [ "tsProtocolMessage", "structts_protocol_message.html", "structts_protocol_message" ],
    [ "tsSensor", "structts_sensor.html", "structts_sensor" ],
    [ "tsSensorControl", "structts_sensor_control.html", "structts_sensor_control" ],
    [ "tsSensorEvent", "structts_sensor_event.html", "structts_sensor_event" ],
    [ "tsSpiffsControl", "structts_spiffs_control.html", "structts_spiffs_control" ],
    [ "tsSpiffsFile", "structts_spiffs_file.html", "structts_spiffs_file" ],
    [ "tsSpiffsStatus", "structts_spiffs_status.html", "structts_spiffs_status" ],
    [ "tsTimekeeperTaskConfiguration", "structts_timekeeper_task_configuration.html", "structts_timekeeper_task_configuration" ],
    [ "tsTimingEntry", "structts_timing_entry.html", "structts_timing_entry" ],
    [ "tsUDPBuffer", "structts_u_d_p_buffer.html", "structts_u_d_p_buffer" ],
    [ "tsUDPControl", "structts_u_d_p_control.html", "structts_u_d_p_control" ],
    [ "tsUDPMessage", "structts_u_d_p_message.html", "structts_u_d_p_message" ],
    [ "tsWifiControl", "structts_wifi_control.html", "structts_wifi_control" ],
    [ "tsWifiTaskConfiguration", "structts_wifi_task_configuration.html", "structts_wifi_task_configuration" ],
    [ "UART_ConfigTypeDef", "struct_u_a_r_t___config_type_def.html", "struct_u_a_r_t___config_type_def" ],
    [ "UART_IntrConfTypeDef", "struct_u_a_r_t___intr_conf_type_def.html", "struct_u_a_r_t___intr_conf_type_def" ]
];