#include "welcome_config.html.h"

const char acWelcome_configHtml[] = {
	"HTTP/1.1 200 OK\r\n"
	"Content-type: text/html\r\n\r\n"
	""
	"<!DOCTYPE html>"
	"<html lang=\"en\">"
	"<head>"
	"    <meta charset=\"UTF-8\" name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
	"    <title>Initial Configuration </title>"
	""
	"    <style>"
	"        * {"
	"            box-sizing: border-box;"
	"        }"
	"        html {"
	"            font-family: \"Lucida Sans\", sans-serif;"
	"        }"
	"        .row::after {"
	"            content: \"\";"
	"            clear: both;"
	"            display: table;"
	"        }"
	"        .form {"
	"        }"
	""
	"        .txtinput {"
	"            width: 100%;"
	"            padding: 15px;"
	"            margin-bottom: 30px;"
	"            font-size: 18px;"
	"            font-family: \"Consolas\", sans-serif;"
	"            color: #596264;"
	""
	"        }"
	"        .inputlbl {"
	"            width: 300px;"
	"            border: 5px;"
	"            padding: auto;"
	"            margin-top: 0px;"
	"            font-size: 24px;"
	"            font-family: \"Consolas\", sans-serif;"
	"        }"
	"        .header {"
	"            background-color: #ff2f3b;"
	"            text-align: left;"
	"            color: #ffffff;"
	"            padding: 15px;"
	"            border-radius: 5px;"
	"            margin-bottom: 10px;"
	"        }"
	""
	"        .info {"
	"            background-color: #cea363;"
	"            text-align: right;"
	"            font-size: 24px;"
	"            color: white;"
	"            padding: 15px;"
	"            border-radius: 15px;"
	"            margin-top: 20px;"
	"        }"
	"        .button {"
	"            width: 100%;"
	"            padding: 15px;"
	"            background-color: white;"
	"            color: #ff6910;"
	"            text-align: center;"
	"            border: 1px solid #ff6910;"
	"            border-radius: 5px;"
	"            font-size: 24px;"
	"        }"
	"        .button:hover {"
	"            background-color: #ff6910;"
	"            color: white;"
	"            transition-duration: 0.2s;"
	"        }"
	"        /* For mobile phones: */"
	"        [class*=\"col-\"] {"
	"            float: left;"
	"            padding: 15px;"
	"            width: 100%;"
	"        }"
	"        @media only screen and (min-width: 1024px) {"
	"            .col-1 {width: 50%;}"
	"            .col-2 {width: 50%;}"
	"            .col-3 {width: 50%;}"
	"            .col-4 {width: 50%;}"
	"            .col-5 {width: 50%;}"
	"            .col-6 {width: 50%;}"
	"            .col-7 {width: 100%;}"
	"            .col-8 {width: 100%;}"
	"            .col-9 {width: 100%;}"
	"            .col-10 {width: 100%;}"
	"            .col-11 {width: 100%;}"
	"            .col-12 {width: 100%;}"
	"        }"
	"        @media only screen and (min-width: 1440px) {"
	"            /* For desktop: */"
	"            .col-1 {width: 8.33%;}"
	"            .col-2 {width: 16.66%;}"
	"            .col-3 {width: 25%;}"
	"            .col-4 {width: 33.33%;}"
	"            .col-5 {width: 41.66%;}"
	"            .col-6 {width: 50%;}"
	"            .col-7 {width: 58.33%;}"
	"            .col-8 {width: 66.66%;}"
	"            .col-9 {width: 75%;}"
	"            .col-10 {width: 83.33%;}"
	"            .col-11 {width: 91.66%;}"
	"            .col-12 {width: 100%;}"
	"        }"
	"    </style>"
	""
	"    <script>"
	"        function sendAPData()"
	"        {"
	"            var xhttp = new XMLHttpRequest();"
	"            wlan = document.getElementById(\"WlanName\").value;"
	"            pswd = document.getElementById(\"WlanPSWD\").value;"
	"            var data = {"
	"                \"WLAN\": wlan,"
	"                \"PSWD\": pswd"
	"            };"
	"            content = JSON.stringify(data);"
	"            xhttp.onreadystatechange = function () {"
	"                if (this.readyState === 4 && this.status === 200) {"
	"                    document.getElementById(\"status\").innerHTML = this.responseText;"
	"                    requestDeviceReset()"
	"                }"
	"            };"
	"            xhttp.open(\"POST\", \"/cgi/connect_wlan\", true);"
	"            xhttp.send(content);"
	"        }"
	""
	"        function requestStatus()"
	"        {"
	"            var xhttp = new XMLHttpRequest();"
	"            xhttp.onreadystatechange = function () {"
	"                if (this.readyState === 4 && this.status === 200) {"
	"                    document.getElementById(\"status\").innerHTML = this.responseText;"
	"                }"
	"            };"
	"            xhttp.open(\"GET\", \"/cgi/status\", true);"
	"            xhttp.send();"
	"        }"
	""
	"        function requestConfigMessage()"
	"        {"
	"            var xhttp = new XMLHttpRequest();"
	"            xhttp.onreadystatechange = function () {"
	"                if (this.readyState === 4 && this.status === 200) {"
	"                    document.getElementById(\"config_message\").innerHTML = this.responseText;"
	"                }"
	"            };"
	"            xhttp.open(\"GET\", \"/cgi/config_message\", true);"
	"            xhttp.send();"
	"        }"
	""
	"        function requestDeviceReset()"
	"        {"
	"            var xhttp = new XMLHttpRequest();"
	"            xhttp.onreadystatechange = function () {"
	"                if (this.readyState === 4 && this.status === 200) {"
	"                    document.getElementById(\"config_message\").innerHTML = \"Device restarting...\";"
	"                }"
	"            };"
	"            xhttp.open(\"GET\", \"/cgi/device_restart\", true);"
	"            xhttp.send();"
	"        }"
	""
	""
	""
	"        requestConfigMessage()"
	"    </script>"
	""
	"</head>"
	"<body>"
	""
	"<div class=\"header col-12\">"
	"    <h1>Swifit device configuration</h1>"
	"</div>"
	""
	"<div class=\"row\">"
	"    <div class=\"col-4 info\">"
	"        <p id=\"status\">Enter your home WLAN's SSID and password.</p>"
	"        <p id=\"config_message\"></p>"
	"    </div>"
	"    <div class=\"col-4\">"
	"        <form action=\"\" class=\"form\">"
	"            <label class=\"inputlbl\" for=\"WlanName\">WLAN Name</label>"
	"            <input class=\"txtinput\" type=\"text\" name=\"WlanName\" id=\"WlanName\" ><br>"
	"            <label class=\"inputlbl\" for=\"WlanPassword\">Password</label>"
	"            <input class=\"txtinput\" type=\"password\" name=\"WlanPassword\" id=\"WlanPSWD\" >"
	"        </form>"
	"        <button class=\"button\" type=\"submit\" onclick=\"sendAPData()\">Submit</button>"
	"    </div>"
	"</div>"
	"</body>"
	"</html>"
};